name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main  # The 'main' branch
      - 'releases/*'  # The release branches

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # A full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2
        with:
          pr-mode: false  # Set to 'true' for pull request mode
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}  # Set the Qodana token as a secret
          QODANA_ENDPOINT: 'https://qodana.cloud'  # Qodana Cloud endpoint
