name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout the actual commit for PR analysis
          fetch-depth: 0  # Ensure full history is available for PR analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2
        with:
          pr-mode: false
          linter: jetbrains/qodana-jvm-community  # Use the community version of Qodana
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}  # You can still use the token for limited features
